// Jenkins Pipeline — add this stage after your Cypress test run.
// Uploads LLVM coverage artifacts to S3 so the MCP server can fetch them.
//
// Prerequisites:
//   - llvm-cov on PATH
//   - AWS CLI configured (or IAM role attached to the Jenkins agent)
//   - COVERAGE_S3_BUCKET set in Jenkins credentials / env

stage('Generate & Upload LLVM Coverage') {
    steps {
        script {
            def tag    = env.BUILD_NUMBER         // e.g. "42" — becomes the {tag}
            def bucket = env.COVERAGE_S3_BUCKET   // set in Jenkins env / credentials
            def binary = "./target/debug/router"  // path to your instrumented binary
            def profdata = "coverage.profdata"

            sh """
                # 1. Merge raw profile data generated by Cypress test run
                llvm-profdata merge -sparse *.profraw -o ${profdata}

                # 2. Export structured JSON (REQUIRED for bucket plan tool)
                llvm-cov export \\
                    --format=json \\
                    --instr-profile=${profdata} \\
                    ${binary} \\
                    > coverage_${tag}.json

                # 3. Generate HTML report
                llvm-cov show \\
                    --format=html \\
                    --instr-profile=${profdata} \\
                    ${binary} \\
                    --output-dir=coverage_html/

                # Rename index.html to index_{tag}.html before upload
                cp coverage_html/index.html coverage_html/index_${tag}.html

                # 4. Upload to S3 (keys match the MCP server's templates)
                aws s3 cp coverage_${tag}.json   s3://${bucket}/coverage_${tag}.json
                aws s3 cp coverage_html/index_${tag}.html s3://${bucket}/index_${tag}.html
                aws s3 sync coverage_html/        s3://${bucket}/html_${tag}/
            """
        }
    }
}
