// Jenkins pipeline snippet — Coverage upload to S3 + trigger sync service
//
// Jenkins (K8s, has S3 access) does:
//   1. Upload line.json + function.json to S3
//   2. Generate pre-signed HTTPS URLs (valid 1 hour)
//   3. POST those URLs to the sync service running on the local machine
//
// The sync service downloads files via pre-signed URLs — no AWS credentials
// needed on the local machine.
//
// Jenkins credentials/env vars required:
//   aws-credentials          — AWS credential binding (for S3 upload)
//   COVERAGE_S3_BUCKET       — e.g. "my-coverage-bucket"
//   COVERAGE_S3_PREFIX       — default: "builds"
//   SYNC_SERVICE_URL         — e.g. "http://your-local-machine:8888/sync"
//   SYNC_API_KEY             — raw key (generated by sync/keygen.py)

pipeline {
    agent any

    environment {
        S3_BUCKET     = credentials('COVERAGE_S3_BUCKET')
        S3_PREFIX     = "${env.COVERAGE_S3_PREFIX ?: 'builds'}"
        BUILD_TAG     = "${env.BUILD_NUMBER}-${env.GIT_COMMIT?.take(8) ?: 'unknown'}"
        S3_BUILD_PATH = "s3://${S3_BUCKET}/${S3_PREFIX}/${BUILD_TAG}"
        SYNC_URL      = credentials('SYNC_SERVICE_URL')
        SYNC_KEY      = credentials('SYNC_API_KEY')
    }

    stages {
        stage('Build & Test') {
            steps {
                sh 'cargo llvm-cov --workspace --json --output-path raw_coverage.json'
            }
        }

        stage('Generate Coverage Reports') {
            steps {
                // Produce line.json and function.json from your coverage tool output.
                // Adjust these commands to match your project.
                sh '''
                    cp index.json line.json
                    cp function_coverage.json function.json
                '''
            }
        }

        stage('Upload to S3') {
            steps {
                withAWS(credentials: 'aws-credentials', region: 'us-east-1') {
                    sh """
                        aws s3 cp line.json     ${S3_BUILD_PATH}/line.json
                        aws s3 cp function.json ${S3_BUILD_PATH}/function.json
                    """
                }
            }
        }

        stage('Trigger Sync') {
            steps {
                withAWS(credentials: 'aws-credentials', region: 'us-east-1') {
                    script {
                        // Generate pre-signed URLs (valid for 1 hour)
                        def lineUrl = sh(
                            script: "aws s3 presign ${S3_BUILD_PATH}/line.json --expires-in 3600",
                            returnStdout: true
                        ).trim()
                        def funcUrl = sh(
                            script: "aws s3 presign ${S3_BUILD_PATH}/function.json --expires-in 3600",
                            returnStdout: true
                        ).trim()

                        def branch = env.GIT_BRANCH?.replace('origin/', '') ?: ''
                        def commit = env.GIT_COMMIT ?: ''

                        def payload = groovy.json.JsonOutput.toJson([
                            build_id:     env.BUILD_TAG,
                            branch:       branch,
                            commit:       commit,
                            line_url:     lineUrl,
                            function_url: funcUrl,
                        ])

                        // POST to sync service on local machine
                        sh """
                            curl -sf \
                              -X POST "${SYNC_URL}" \
                              -H "Authorization: Bearer ${SYNC_KEY}" \
                              -H "Content-Type: application/json" \
                              -d '${payload}' \
                            && echo "Sync triggered for build ${BUILD_TAG}" \
                            || echo "WARNING: sync trigger failed (build still uploaded to S3)"
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            sh 'rm -f line.json function.json raw_coverage.json'
        }
    }
}
